CSWTestBookLibrary/BookLibraryWeb/Controllers/BookLibraryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BookLibraryWeb;
using BookLibraryData;

namespace BookLibraryWeb.Controllers
{
    /// <summary>
    /// Book Library Controller Class
    /// </summary>
    public class BookLibraryController : Controller
    {
        private static IEnumerable<SelectListItem> items = new List<SelectListItem>();

        /// <summary>
        /// Indexes this instance.
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View((new BookLibraryDBContext()).GetAllBooks());
        }

        /// <summary>
        /// Searches the by author.
        /// </summary>
        /// <param name="book">The book.</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult SearchByAuthor(Book book)
        {
            using (var model = new BookLibraryDBContext())
            {
                try
                {
                    return View(model.GetBooksByAuthor(book.Author).ToList());
                }
                catch
                {
                    return View();
                }
            }
        }

        /// <summary>
        /// Searches the by author.
        /// </summary>
        /// <returns></returns>
        public ActionResult SearchByAuthor()
        {
            return View();
        }

        /// <summary>
        /// Sets the type of the category.
        /// </summary>
        private void SetCategoryType()
        {
            if (items.Count() == 0)
            {
                using (var model = new BookLibraryDBContext())
                {
                    IList<Category> values = model.Categories.ToList();
                    items = from value in values
                            select new SelectListItem
                            {
                                Text = value.Name,
                                Value = value.Id.ToString(),
                            };
                }
            }

            ViewBag.CategoryType = items;
        }

        /// <summary>
        /// Searches the by category.
        /// </summary>
        /// <returns></returns>
        public ActionResult SearchByCategory()
        {
            this.SetCategoryType();
            return View();
        }

        /// <summary>
        /// Categories the chosen.
        /// </summary>
        /// <param name="CategoryType">Type of the category.</param>
        /// <returns></returns>
        public ViewResult CategoryChosen(string CategoryType)
        {
            this.SetCategoryType();
            using (var model = new BookLibraryDBContext())
            {
                int id = 0;
                if (int.TryParse(CategoryType, out id))
                {
                    return View("SearchByCategory", model.GetBooksByCategory(id).ToList());
                }
            }

            return View();
        }

        /// <summary>
        /// Authors the search.
        /// </summary>
        /// <param name="author">The author.</param>
        /// <returns></returns>
        public ActionResult AuthorSearch(string author)
        {
            using (var model = new BookLibraryDBContext())
            {
                try
                {
                    return View("SearchByAuthor", model.GetBooksByAuthor(author));
                }
                catch
                {
                    return View();
                }
            }
        }

    }
}

CSWTestBookLibrary/BookLibraryWeb/Views/BookLibrary/Index.cshtml
@model IEnumerable<BookLibraryData.Book>
@{
    ViewBag.Title = "Book Library";
}

<h2>List of Books</h2>

<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Author)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Category)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Author)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Category.Name)
        </td>
    </tr>
}

</table>

CSWTestBookLibrary/BookLibraryWeb/Views/BookLibrary/SearchByAuthor.cshtml
@model IEnumerable<BookLibraryData.Book>
@{
    ViewBag.Title = "Search By Author";
}

<h2>Enter your preferred author:</h2>

@using (Html.BeginForm("AuthorSearch", "BookLibrary")) {
        <div class="editor-field">
           @Html.TextBox("author",
                 String.Empty, 
                 new { maxlength = 50, minlength = 3 })
        </div>
        <p>
            <input type="submit" value="Search" />
        </p>
}

<table>
    @if (Model != null && Model.Count() > 0)
    {
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Author)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
        </tr>
   
        foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Author)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category.Name)
            </td>
        </tr>
        }
    }
</table>

<div class="back-to-list">
    @Html.ActionLink("Back to List", "Index")
</div>

CSWTestBookLibrary/BookLibraryWeb/Views/BookLibrary/SearchByCategory.cshtml
@model IEnumerable<BookLibraryData.Book>
@{
    ViewBag.Title = "Search by Category";
}

<h2>Select tha book category:</h2>

@using (Html.BeginForm("CategoryChosen", "BookLibrary", FormMethod.Get))
{
    @Html.DropDownList("CategoryType")
    <input type= "submit" style="margin-left:20px;" value="Search" />
}

<table>
    @if (Model != null && Model.Count() > 0)
    {
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Author)
            </th>
        </tr>
   
        foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Author)
            </td>
        </tr>
        }
    }
</table>

<div class="back-to-list">
    @Html.ActionLink("Back to List", "Index")
</div>

CSWTestBookLibrary/BookLibraryWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - Book Library</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <img src="~/Images/books.jpg" />
                </div>
                <div class="float-right" style="margin-top: 65px;">
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Books List", "Index", "BookLibrary")</li>
                            <li>@Html.ActionLink("Search Books by  Author", "SearchByAuthor", "BookLibrary")</li>
                            <li>@Html.ActionLink("Search Books by Category", "SearchByCategory", "BookLibrary")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - Book Library Application</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>